version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rewards
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DEBUG=true
    depends_on:
      - db
    command: api

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rewards
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    depends_on:
      - db
    command: notebook

volumes:
  postgres_data:
